=== Javs07AM/tecweb/practicas/p11/serviciovod_ep.dtd
<!ENTITY % regiones "MEX|USA|ESP|ARG|KOR">

<!ELEMENT CatalogoVOD (cuenta, contenido)>

<!ELEMENT cuenta (perfiles)>
<!ATTLIST cuenta
    correo CDATA #REQUIRED
>

<!ELEMENT perfiles (perfil+)>

<!ELEMENT perfil EMPTY>
<!ATTLIST perfil
    usuario CDATA #REQUIRED
    idioma CDATA #REQUIRED
>

<!ELEMENT contenido (peliculas+, series)>

<!ELEMENT peliculas (titulo+)>
<!ATTLIST peliculas
    genero CDATA #REQUIRED
>

<!ELEMENT titulo EMPTY>
<!ATTLIST titulo
    nombre CDATA #REQUIRED
    duracion CDATA #REQUIRED
    region CDATA "USA"
>

<!ELEMENT series (genero+)>
<!ELEMENT genero EMPTY>
<!ATTLIST genero
    nombre CDATA #REQUIRED
    region CDATA "USA"
>

=== Javs07AM/tecweb/practicas/p14/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="catalogovod.xsl" type="text/xsl"?>
<!DOCTYPE CatalogoVOD SYSTEM "serviciovod_ep.dtd">
<CatalogoVOD>
    <cuenta correo="javs@syntax.com">
        <!-- Perfiles -->
        <perfiles>
            <!-- Perfil 1 -->
            <perfil usuario="Javs" idioma="Español" />
            <!-- Perfil 2 -->
            <perfil usuario="Gojo" idioma="Japonés" />
        </perfiles>
    </cuenta>
    <contenido>
        <peliculas region="USA">
            <genero nombre="Accion">
                <titulo duracion="122 minutos">Heart of Stone</titulo>
                <titulo duracion="118 minutos">The Mother</titulo>
            </genero>
            <genero nombre="Comedia">
                <titulo duracion="95 minutos">Son como niños</titulo>
                <titulo duracion="100 minutos">¿Dónde están las rubias?</titulo>
            </genero>
        </peliculas>
        <series region="USA">
            <genero nombre="Drama">
                <titulo duracion="50 minutos">Dr. House</titulo>
                <titulo duracion="50 minutos">Game of Thrones</titulo>
            </genero>
            <genero nombre="Documental">
                <titulo duracion="40 minutos">The Act</titulo>
                <titulo duracion="50 minutos">The Last Dance</titulo>
            </genero>
        </series>
    </contenido>
</CatalogoVOD>

=== Javs07AM/tecweb/practicas/p11/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoVOD SYSTEM "serviciovod_ep.dtd">
<CatalogoVOD>
    <!-- Cuenta 1 -->
    <cuenta correo="javs@syntax.com">
        <!-- Perfiles -->
        <perfiles>
            <!-- Perfil 1 -->
            <perfil usuario="Javs" idioma="Español" />
            <!-- Perfil 2 -->
            <perfil usuario="Gojo" idioma="Japonés" />
        </perfiles>
    </cuenta>

    <!-- Contenido -->
    <contenido>
        <!-- Género 1 -->
        <peliculas genero="Acción">
            <!-- Títulos de Películas -->
            <titulo nombre="Heart of Stone" duracion="122 minutos" region="USA" />
            <titulo nombre="The Mother" duracion="118 minutos" region="KOR" />
            <titulo nombre="Spiderman-A través del universo" duracion="140 minutos" region="ESP" />
            <titulo nombre="Spider-Man 3" duracion="139 minutos" region="MEX" />
        </peliculas>

        <!-- Género 2 -->
        <peliculas genero="Comedia">
            <!-- Títulos de Películas -->
            <titulo nombre="Son como niños" duracion="95 minutos" region="USA" />
            <titulo nombre="¿Dónde están las rubias?" duracion="100 minutos" region="USA" />
            <titulo nombre="Scary Movie" duracion="90 minutos" region="USA" />
            <titulo nombre="¿Y qué pasó ayer?" duracion="105 minutos" region="USA" />
        </peliculas>

        <!-- Géneros de Programas -->
        <series>
            <!-- Género 1 -->
            <genero nombre="Drama" region="USA" />
            <!-- Género 2 -->
            <genero nombre="Documental" region="USA" />
        </series>
    </contenido>
</CatalogoVOD>
